/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Address = IDL.Record({
  'zip' : IDL.Text,
  'street' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'state' : IDL.Text,
});
export const Hospital = IDL.Record({
  'id' : IDL.Nat,
  'latitude' : IDL.Float64,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'email' : IDL.Text,
  'longitude' : IDL.Float64,
  'address' : Address,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const InventoryItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'available' : IDL.Bool,
  'hospitalId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
});
export const Treatment = IDL.Record({
  'id' : IDL.Nat,
  'description' : IDL.Text,
  'conditionName' : IDL.Text,
  'hospitalId' : IDL.Nat,
  'treatmentName' : IDL.Text,
});
export const SearchResult = IDL.Record({
  'hospital' : Hospital,
  'matchingTreatments' : IDL.Vec(Treatment),
  'matchingItems' : IDL.Vec(InventoryItem),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addInventoryItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Bool, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addTreatment' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createHospital' : IDL.Func(
      [
        IDL.Text,
        Address,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'getAllHospitals' : IDL.Func([], [IDL.Vec(Hospital)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHospitalDetails' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'hospital' : Hospital,
          'inventory' : IDL.Vec(InventoryItem),
          'treatments' : IDL.Vec(Treatment),
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeInventoryItem' : IDL.Func([IDL.Nat], [], []),
  'removeTreatment' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchHospitals' : IDL.Func([IDL.Text], [IDL.Vec(SearchResult)], ['query']),
  'updateHospital' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        Address,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateInventoryItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Bool, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'updateTreatment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Address = IDL.Record({
    'zip' : IDL.Text,
    'street' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'state' : IDL.Text,
  });
  const Hospital = IDL.Record({
    'id' : IDL.Nat,
    'latitude' : IDL.Float64,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'email' : IDL.Text,
    'longitude' : IDL.Float64,
    'address' : Address,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const InventoryItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'available' : IDL.Bool,
    'hospitalId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
  });
  const Treatment = IDL.Record({
    'id' : IDL.Nat,
    'description' : IDL.Text,
    'conditionName' : IDL.Text,
    'hospitalId' : IDL.Nat,
    'treatmentName' : IDL.Text,
  });
  const SearchResult = IDL.Record({
    'hospital' : Hospital,
    'matchingTreatments' : IDL.Vec(Treatment),
    'matchingItems' : IDL.Vec(InventoryItem),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addInventoryItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Bool, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addTreatment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createHospital' : IDL.Func(
        [
          IDL.Text,
          Address,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'getAllHospitals' : IDL.Func([], [IDL.Vec(Hospital)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHospitalDetails' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'hospital' : Hospital,
            'inventory' : IDL.Vec(InventoryItem),
            'treatments' : IDL.Vec(Treatment),
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeInventoryItem' : IDL.Func([IDL.Nat], [], []),
    'removeTreatment' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchHospitals' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SearchResult)],
        ['query'],
      ),
    'updateHospital' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          Address,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateInventoryItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Bool, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'updateTreatment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };