/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'zip' : string,
  'street' : string,
  'country' : string,
  'city' : string,
  'state' : string,
}
export interface Hospital {
  'id' : bigint,
  'latitude' : number,
  'owner' : Principal,
  'name' : string,
  'description' : string,
  'email' : string,
  'longitude' : number,
  'address' : Address,
  'phone' : string,
}
export interface InventoryItem {
  'id' : bigint,
  'name' : string,
  'unit' : string,
  'available' : boolean,
  'hospitalId' : bigint,
  'quantity' : bigint,
  'category' : string,
}
export interface SearchResult {
  'hospital' : Hospital,
  'matchingTreatments' : Array<Treatment>,
  'matchingItems' : Array<InventoryItem>,
}
export interface Treatment {
  'id' : bigint,
  'description' : string,
  'conditionName' : string,
  'hospitalId' : bigint,
  'treatmentName' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addInventoryItem' : ActorMethod<
    [bigint, string, string, boolean, bigint, string],
    bigint
  >,
  'addTreatment' : ActorMethod<[bigint, string, string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createHospital' : ActorMethod<
    [string, Address, number, number, string, string, string],
    bigint
  >,
  'getAllHospitals' : ActorMethod<[], Array<Hospital>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHospitalDetails' : ActorMethod<
    [bigint],
    {
      'hospital' : Hospital,
      'inventory' : Array<InventoryItem>,
      'treatments' : Array<Treatment>,
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeInventoryItem' : ActorMethod<[bigint], undefined>,
  'removeTreatment' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchHospitals' : ActorMethod<[string], Array<SearchResult>>,
  'updateHospital' : ActorMethod<
    [bigint, string, Address, number, number, string, string, string],
    undefined
  >,
  'updateInventoryItem' : ActorMethod<
    [bigint, string, string, boolean, bigint, string],
    undefined
  >,
  'updateTreatment' : ActorMethod<[bigint, string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];